-- MySQL Script generated by MySQL Workbench
-- Mon Jan 24 12:15:45 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema EMS_V2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema EMS_V2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EMS_V2` DEFAULT CHARACTER SET utf8 ;
USE `EMS_V2` ;

-- -----------------------------------------------------
-- Table `EMS_V2`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EMS_V2`.`User` (
  `Id_user` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(50) NOT NULL,
  `Password` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`Id_user`),
  UNIQUE INDEX `idDashboard_UNIQUE` (`Id_user` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EMS_V2`.`Company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EMS_V2`.`Company` (
  `Id_Company` INT NOT NULL AUTO_INCREMENT,
  `Company_name` VARCHAR(45) NOT NULL,
  `Country` VARCHAR(20) NOT NULL,
  `User_Id_user` INT NOT NULL,
  PRIMARY KEY (`Id_Company`),
  UNIQUE INDEX `Id_Company_UNIQUE` (`Id_Company` ASC),
  INDEX `fk_Company_User1_idx` (`User_Id_user` ASC),
  CONSTRAINT `fk_Company_User1`
    FOREIGN KEY (`User_Id_user`)
    REFERENCES `EMS_V2`.`User` (`Id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EMS_V2`.`Plant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EMS_V2`.`Plant` (
  `idPlant` INT NOT NULL AUTO_INCREMENT,
  `name_plant` VARCHAR(30) NOT NULL,
  `User_Id_User` INT NOT NULL,
  `Company_Id_Company` INT NOT NULL,
  PRIMARY KEY (`idPlant`),
  UNIQUE INDEX `idPlant_UNIQUE` (`idPlant` ASC),
  INDEX `fk_Plant_Company1_idx` (`Company_Id_Company` ASC),
  CONSTRAINT `fk_Plant_Company1`
    FOREIGN KEY (`Company_Id_Company`)
    REFERENCES `EMS_V2`.`Company` (`Id_Company`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EMS_V2`.`type_medition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EMS_V2`.`type_medition` (
  `Id_Medition` INT NOT NULL AUTO_INCREMENT,
  `Name_medition` INT NOT NULL,
  `Unity_type` VARCHAR(5) NOT NULL,
  `Plant_idPlant` INT NOT NULL,
  PRIMARY KEY (`Id_Medition`),
  UNIQUE INDEX `idSensor_UNIQUE` (`Id_Medition` ASC),
  INDEX `fk_type_medition_Plant1_idx` (`Plant_idPlant` ASC),
  CONSTRAINT `fk_type_medition_Plant1`
    FOREIGN KEY (`Plant_idPlant`)
    REFERENCES `EMS_V2`.`Plant` (`idPlant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EMS_V2`.`Sensors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EMS_V2`.`Sensors` (
  `Id_Sensor` INT NOT NULL AUTO_INCREMENT,
  `Name_Sensor` VARCHAR(10) NOT NULL,
  `type_medition_Id_Medition` INT NOT NULL,
  PRIMARY KEY (`Id_Sensor`),
  UNIQUE INDEX `Id_Sensor_UNIQUE` (`Id_Sensor` ASC),
  INDEX `fk_Sensors_type_medition1_idx` (`type_medition_Id_Medition` ASC),
  CONSTRAINT `fk_Sensors_type_medition1`
    FOREIGN KEY (`type_medition_Id_Medition`)
    REFERENCES `EMS_V2`.`type_medition` (`Id_Medition`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EMS_V2`.`Maintenance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EMS_V2`.`Maintenance` (
  `Id_Maintenance` INT NOT NULL AUTO_INCREMENT,
  `Name_M` VARCHAR(13) NULL,
  `User_Id_user` INT NOT NULL,
  PRIMARY KEY (`Id_Maintenance`),
  UNIQUE INDEX `Id_Maintenance_UNIQUE` (`Id_Maintenance` ASC),
  INDEX `fk_Maintenance_User1_idx` (`User_Id_user` ASC),
  CONSTRAINT `fk_Maintenance_User1`
    FOREIGN KEY (`User_Id_user`)
    REFERENCES `EMS_V2`.`User` (`Id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EMS_V2`.`Reading_HVAC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EMS_V2`.`Reading_HVAC` (
  `Id_RH` INT NOT NULL,
  `Brand` VARCHAR(30) NOT NULL,
  `Indoor` INT NOT NULL,
  `Outdoor` INT NOT NULL,
  `HVAC_Id-HVAC` INT NOT NULL,
  `Maintenance_Id_Maintenance` INT NOT NULL,
  PRIMARY KEY (`Id_RH`),
  UNIQUE INDEX `Id_RH_UNIQUE` (`Id_RH` ASC),
  INDEX `fk_Reading_HVAC_Maintenance1_idx` (`Maintenance_Id_Maintenance` ASC),
  CONSTRAINT `fk_Reading_HVAC_Maintenance1`
    FOREIGN KEY (`Maintenance_Id_Maintenance`)
    REFERENCES `EMS_V2`.`Maintenance` (`Id_Maintenance`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EMS_V2`.`Status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EMS_V2`.`Status` (
  `Is_Status` INT NOT NULL AUTO_INCREMENT,
  `Name_S` VARCHAR(15) NOT NULL,
  `Reading_HVAC_Id_RH` INT NOT NULL,
  PRIMARY KEY (`Is_Status`),
  UNIQUE INDEX `Is_Status_UNIQUE` (`Is_Status` ASC),
  INDEX `fk_Status_Reading_HVAC1_idx` (`Reading_HVAC_Id_RH` ASC),
  CONSTRAINT `fk_Status_Reading_HVAC1`
    FOREIGN KEY (`Reading_HVAC_Id_RH`)
    REFERENCES `EMS_V2`.`Reading_HVAC` (`Id_RH`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EMS_V2`.`LMOC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EMS_V2`.`LMOC` (
  `ID_LMOC` INT NOT NULL AUTO_INCREMENT,
  `Maintenance_Id_Maintenance` INT NOT NULL,
  PRIMARY KEY (`ID_LMOC`),
  UNIQUE INDEX `ID_LMOC_UNIQUE` (`ID_LMOC` ASC),
  INDEX `fk_LMOC_Maintenance1_idx` (`Maintenance_Id_Maintenance` ASC),
  CONSTRAINT `fk_LMOC_Maintenance1`
    FOREIGN KEY (`Maintenance_Id_Maintenance`)
    REFERENCES `EMS_V2`.`Maintenance` (`Id_Maintenance`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EMS_V2`.`Status_LMOC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EMS_V2`.`Status_LMOC` (
  `Is_Status` INT NOT NULL AUTO_INCREMENT,
  `Name_S` VARCHAR(15) NOT NULL,
  `LMOC_ID_LMOC` INT NOT NULL,
  PRIMARY KEY (`Is_Status`),
  UNIQUE INDEX `Is_Status_UNIQUE` (`Is_Status` ASC),
  INDEX `fk_Status_LMOC_LMOC1_idx` (`LMOC_ID_LMOC` ASC),
  CONSTRAINT `fk_Status_LMOC_LMOC1`
    FOREIGN KEY (`LMOC_ID_LMOC`)
    REFERENCES `EMS_V2`.`LMOC` (`ID_LMOC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EMS_V2`.`Reading_General`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EMS_V2`.`Reading_General` (
  `Id_RG` INT NOT NULL AUTO_INCREMENT,
  `Error_code` INT NOT NULL,
  `Date_Time` DATETIME NOT NULL,
  `Plant` INT NOT NULL,
  `Description` TINYTEXT NOT NULL,
  `Maintenance_Id_Maintenance` INT NOT NULL,
  PRIMARY KEY (`Id_RG`),
  UNIQUE INDEX `Id_General_UNIQUE` (`Id_RG` ASC) VISIBLE,
  INDEX `fk_General_Maintenance1_idx` (`Maintenance_Id_Maintenance` ASC),
  CONSTRAINT `fk_General_Maintenance1`
    FOREIGN KEY (`Maintenance_Id_Maintenance`)
    REFERENCES `EMS_V2`.`Maintenance` (`Id_Maintenance`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EMS_V2`.`Actions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EMS_V2`.`Actions` (
  `Id_Actions` INT NOT NULL,
  `Name_action` VARCHAR(50) NOT NULL,
  `General_Id_General` INT NOT NULL,
  PRIMARY KEY (`Id_Actions`),
  INDEX `fk_Actions_General1_idx` (`General_Id_General` ASC),
  CONSTRAINT `fk_Actions_General1`
    FOREIGN KEY (`General_Id_General`)
    REFERENCES `EMS_V2`.`Reading_General` (`Id_RG`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EMS_V2`.`Shift`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EMS_V2`.`Shift` (
  `Id_Shift` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Start Time` TIME NOT NULL,
  `End_Time` TIME NOT NULL,
  `Plant_idPlant` INT NOT NULL,
  PRIMARY KEY (`Id_Shift`),
  INDEX `fk_Shift_Plant1_idx` (`Plant_idPlant` ASC),
  CONSTRAINT `fk_Shift_Plant1`
    FOREIGN KEY (`Plant_idPlant`)
    REFERENCES `EMS_V2`.`Plant` (`idPlant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EMS_V2`.`Reading`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EMS_V2`.`Reading` (
  `ID_Read` INT NOT NULL,
  `Date_time` DATETIME NOT NULL,
  `Sensors_Id_Sensor` INT NOT NULL,
  `Value` DECIMAL(3) NOT NULL,
  INDEX `fk_Reading_Sensors1_idx` (`Sensors_Id_Sensor` ASC),
  CONSTRAINT `fk_Reading_Sensors1`
    FOREIGN KEY (`Sensors_Id_Sensor`)
    REFERENCES `EMS_V2`.`Sensors` (`Id_Sensor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EMS_V2`.`Reading_LMOC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EMS_V2`.`Reading_LMOC` (
  `idR_LMOC` INT NOT NULL AUTO_INCREMENT,
  `N_Order` INT NOT NULL,
  `Created` DATETIME NOT NULL,
  `LMOC_ID_LMOC` INT NOT NULL,
  PRIMARY KEY (`idR_LMOC`),
  UNIQUE INDEX `idR_LMOC_UNIQUE` (`idR_LMOC` ASC),
  UNIQUE INDEX `N_Order_UNIQUE` (`N_Order` ASC),
  INDEX `fk_Reading_LMOC_LMOC1_idx` (`LMOC_ID_LMOC` ASC),
  CONSTRAINT `fk_Reading_LMOC_LMOC1`
    FOREIGN KEY (`LMOC_ID_LMOC`)
    REFERENCES `EMS_V2`.`LMOC` (`ID_LMOC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
